type Question = { entry: number; answer: string | string[]; multiple: boolean };

export const questions: Question[] = [
  { entry: 1854161817, answer: ["Nam", "Nữ"], multiple: false },
  {
    entry: 1704872820,
    answer: ["18 - 22 tuổi", "23 - 27 tuổi"],
    multiple: false,
  },
  {
    entry: 502015944,
    answer: ["Sinh viên", "Người đi làm"],
    multiple: false,
  },
  {
    entry: 1287706313,
    answer: [
      "Ít hơn 1 năm",
      "1-3 năm",
      "Hơn 3 năm",
      "Tôi không thường xuyên xem phim siêu anh hùng",
    ],
    multiple: false,
  },
  {
    entry: 1586308767,
    answer: [
      "Iron Man (2008)",
      "Captain America: The First Avenger (2011)",
      "Iron Man 2 (2010)",
      "The Avengers (2012)",
      "Thor: The Dark World (2013)",
      "Captain America: The Winter Soldier (2014)",
      "Avengers: Age of Ultron (2015)",
      "Captain America: Civil War (2016)",
      "Doctor Strange (2016)",
    ],
    multiple: true,
  },
  {
    entry: 1448767463,
    answer: [
      "Rạp chiếu phim",
      "Xem online trên nền tảng OTT (Netflix, Disney+, v.v.)",
      "Xem qua TV hoặc đĩa DVD",
    ],
    multiple: true,
  },
  {
    entry: 882317043,
    answer: [
      "Trang phục ôm sát và khiên Vibranium",
      "Lãnh đạo",
      "Lòng yêu nước",
      "Công lý và lẽ phải",
      "Hình ảnh người lính hoàn hảo",
      "Tinh thần chính nghĩa",
      "Sự hy sinh vì tự do và dân chủ",
      "Bất bại",
      "Tình bạn và sự đoàn kết",
      "Chris Evans",
      "Bảo vệ hòa bình",
    ],
    multiple: true,
  },
  {
    entry: 1016740613,
    answer: [
      "Nội dung phim hấp dẫn",
      "Nhân vật Captain America truyền cảm hứng",
      "Ảnh hưởng từ bạn bè hoặc mạng xã hội",
      "Tôi yêu thích các bộ phim của Marvel",
      "Đồ họa và kỹ xảo đẹp mắt",
      "Tò mò về thông điệp và ý nghĩa mà phim truyền tải",
    ],
    multiple: true,
  },
  {
    entry: 61702447,
    answer: [
      "Là nhân vật trung tâm dẫn dắt cốt truyện",
      "Là một nhân vật biểu tượng nhưng không quá nổi bật",
      "Là một nhân vật phụ trong tổng thể câu chuyện lớn của Marvel",
      "Tôi không cảm nhận được vai trò quan trọng nào",
    ],
    multiple: false,
  },
  {
    entry: 97471259,
    answer: [
      "Lòng yêu nước và tinh thần chính nghĩa mạnh mẽ",
      "Sự hy sinh và cống hiến vì lợi ích cộng đồng",
      "Khả năng lãnh đạo và sự kiên định với lý tưởng",
      "Tính cách chân thành, gần gũi và nhân văn hơn",
      "Sự trung thành tuyệt đối với bạn bè và đồng đội",
      "Sự đơn giản và không cầu kỳ trong hình tượng",
      "Không có điểm khác biệt đáng kể",
    ],
    multiple: true,
  },
  {
    entry: 79782713,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 225498981,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 73304255,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 801886448,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 1150682640,
    answer: [
      "Văn hóa Mỹ hiện đại và tinh thần dân chủ",
      "Sức mạnh quân sự và vai trò toàn cầu của Mỹ",
      "Tư tưởng tự do và công bằng xã hội",
      "Sự cống hiến và tinh thần lãnh đạo thế giới",
      "Sự phát triển của nước Mỹ",
      "Không cảm thấy ảnh hưởng",
    ],
    multiple: true,
  },
  {
    entry: 1655801403,
    answer: ["Đồng ý", "Hoàn toàn đồng ý"],
    multiple: false,
  },
  {
    entry: 34021993,
    answer: [
      "Có, tôi thấy hình ảnh Mỹ trở nên tích cực hơn",
      "Có, nhưng tôi thấy ảnh hưởng không đáng kể",
      "Không, tôi không cảm thấy thay đổi",
      "Không, tôi có ấn tượng tiêu cực hơn về Mỹ sau khi xem",
    ],
    multiple: false,
  },
  {
    entry: 151309595,
    answer: [
      "Lòng yêu nước",
      "Chủ nghĩa cá nhân",
      "Tinh thần chính nghĩa",
      "Quyền tự do và bình đẳng",
      "Sức mạnh quân sự",
      "Chủ nghĩa tập thể và đoàn kết",
      "Tôi không nhận thấy yếu tố nào đặc biệt",
    ],
    multiple: true,
  },
  {
    entry: 10701847,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 1198183147,
    answer: [
      "Tìm hiểu thêm về văn hóa, lịch sử Mỹ hoặc thế giới siêu anh hùng",
      "Captain America truyền cảm hứng và ảnh hưởng tích cực đến suy nghĩ và lối sống của bạn",
      "Muốn “bắt trend” khi mọi người đang đi xem và bàn luận sôi nổi",
      "Chỉ vì xem cùng gia đình, bạn bè hoặc người quen nên mới đi xem",
      "Thư giãn, giải trí, và tận hưởng hành động, kỹ xảo đẹp mắt",
    ],
    multiple: true,
  },
  {
    entry: 736271714,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 1276496818,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 373078928,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 841515068,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 1325302007,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 1137757914,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 439309348,
    answer: [
      "Thể hiện chiều sâu tâm lí nhân vật",
      "Tăng tính giải trí và hài hước",
      "Kể những câu chuyện có liên hệ với khán giả toàn cầu",
      "Giảm bớt yếu tố “chính trị” hoặc biểu tượng quốc gia",
      "Tập trung vào các giá trị nhân văn phổ quát",
    ],
    multiple: true,
  },
  {
    entry: 1288042065,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 474321869,
    answer: [
      "Hình mẫu nhân vật anh hùng",
      "Nội dung và câu chuyện sâu sắc",
      "Hành động và kỹ xảo điện ảnh",
      "Ý nghĩa hoặc thông điệp mà phim truyền tải",
      "Sự hài hước và giải trí",
    ],
    multiple: false,
  },
  {
    entry: 1398345336,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 1056916366,
    answer: ["4", "5"],
    multiple: false,
  },
  {
    entry: 408620633,
    answer: "",
    multiple: false,
  },
];
